### ISSUE TITLE
Is it possible dont suppress empty lines?

### ISSUE THREAD

**Issue by shab2** [shlomif/perl-Config-IniFiles#10]
Hi!

I use config file with some empty lines. I want change parameter and Rewrite config.
But I see RewriteConfig func removed some empty lines. Should you advise me how dont remove any empty lines?
Thank you.

# cat 1.pl
#!/usr/bin/perl
use Config::IniFiles;
my $file = './2.conf';
my $cfg = Config::IniFiles->new( -file => $file, -fallback => 'GENERAL' );
$cfg->setval ('amrit', 'type', 'boy friend');
$cfg->RewriteConfig;

example=============================
```
# cat 2.conf

#general section
type=1   # general

[amrit]
type=boy friend

#amrit2 section

[amrit2]
type=friend

root@db-dev-83:~
# ./1.pl; cat 2.conf
#general section
type=1   # general

[amrit]
type=boy friend

#amrit2 section
[amrit2]
type=friend
==========================
```

**Comment by shlomif** [comment]
Hi @shab2 ! I honestly don't understand the exact issue due to lack of coherency. Please see https://perl-begin.org/tutorials/bad-elements/ and write a self-contained https://metacpan.org/pod/Test::More script: http://sscce.org/ . Thanks!

**Comment by shab2** [comment]
- Lets learn Perl-Bible, if you want use my module - you says for me. I case another. Thanks

**Comment by shlomif** [comment]
>     * Lets learn Perl-Bible, if you want use my module - you says for me. I case another. Thanks

Just a note that the English grammar in that sentence seems awful.
