### ISSUE TITLE
Checks saved owner:group file

### ISSUE THREAD

**Issue by shab2** [shlomif/perl-Config-IniFiles#11]
Hi,
Im asking to edit ini-file 
ls -lh /etc/grafana/grafana.ini
-rw-r----- 1 root **grafana** 49K Oct 13 14:13 /etc/grafana/grafana.ini
then I use module to edit fields and Rewrite function to save changes, then I have
-rw-r----- 1 root **root** 49K Oct 13 14:13 /etc/grafana/grafana.ini

Please advise me how to dont change owner permissions on edited file?
Thank you

**Comment by shlomif** [comment]
Hi Alexander!

On Thu, 13 Oct 2022 04:40:48 -0700
Alexander Shaburov ***@***.***> wrote:

> Hi,
> Im asking to edit ini-file 
> ls -lh /etc/grafana/grafana.ini
> -rw-r----- 1 root **grafana** 49K Oct 13 14:13 /etc/grafana/grafana.ini
> then I use module to edit fields and Rewrite function to save changes, then I
> have -rw-r----- 1 root **root** 49K Oct 13 14:13 /etc/grafana/grafana.ini
> 
> Please advise me how to dont change owner permissions on edited file?
> Thank you
> 

Would a separate, explicit, "perldoc -f chown" call be good enough?


-- 

Shlomi Fish       https://www.shlomifish.org/
https://youtu.be/GoEn1YfYTBM - Tiffany Alvord - “Fall Together”

SGlau: I suppose serving here at the NSA is also one of your 99 problems?
Daniel: Hey, this place is at least ninety of my problems.
    — https://www.shlomifish.org/humour/Summerschool-at-the-NSA/

Please reply to list if it's a mailing list post - https://shlom.in/reply .

**Comment by shab2** [comment]
You can't complain that your 99 children are taking up too much of your time. It's time to make one of them better. If someone called himself an editor, then he should only edit, but should not change the owner. 
I think your separate, explicit, "perldoc -f chown" call would be good enough.

**Comment by shlomif** [comment]
hi Alexander.

On Thu, 13 Oct 2022 11:16:08 -0700
Alexander Shaburov ***@***.***> wrote:

> You can't complain that your 99 children are taking up too much of your time.
> It's time to make one of them better. If someone called himself an editor,
> then he should only edit, but should not change the owner. I think a
> separate, explicit, "perldoc -f chown" call whould be good enough.
> 

I was not complaining, just providing a workaround. Also see
https://www.shlomifish.org/humour/fortunes/show.cgi?id=smg-about-giving-back-money-and-time
and according to https://github.com/shlomif?tab=repositories I have 967 GH
repos, mostly public ones, and some house many children.

-- 

Shlomi Fish       https://www.shlomifish.org/
Apple Inc. is Evil - https://www.shlomifish.org/open-source/anti/apple/

There is an IGLU Cabal, but its only purpose is to deny the existence of an
IGLU Cabal.
    — Martha Greenberg, https://www.shlomifish.org/humour/fortunes/tinic.html

Please reply to list if it's a mailing list post - https://shlom.in/reply .
