### ISSUE TITLE
support .toml files with -toml_compat (like -php_compat)

### ISSUE THREAD

**Issue by Sadrak** [shlomif/perl-Config-IniFiles#8]
We are using Config::IniFiles for many years and would like to use also .toml-files. After some first tests it would be easy to allow a -toml_compat to respect some .toml specific syntax (not all).

Would you accept such a feature?

I guess one bigger problem would be the multi-section possibility from .toml-files, which -toml_compat simple won't support.

**Comment by shlomif** [comment]
@Sadrak : I feel that one should use a more TOML-oriented API to read and write TOML files properly, and trying to adapt C::IniFiles for that would be a https://en.wikipedia.org/wiki/False_friend and misleading and possibly destructive. What do you think?

**Comment by shlomif** [comment]
@Sadrak : hi, what do you think?

**Comment by Sadrak** [comment]
Yeah, I understand this absolutly and was thinking about a Config::TomlFiles module with exact the same behavior but toml as fileformat. Simple this feature would be only usefull for our case and feels like a false friend.

**Comment by shlomif** [comment]
On Tue, 04 Feb 2020 08:37:47 -0800
Felix Ostmann <notifications@github.com> wrote:

> Yeah, I understand this absolutly and was thinking about a Config::TomlFiles
> module with exact the same behavior but toml as fileformat. Simple this
> feature would be only usefull for our case and feels like a false friend.
> 

Thanks for the reply, Felix!

-- 

Shlomi Fish       https://www.shlomifish.org/
https://youtu.be/GoEn1YfYTBM - Tiffany Alvord - “Fall Together”

If I had any humility, I would be perfect.
    — Ted Turner

Please reply to list if it's a mailing list post - http://shlom.in/reply .
