### ISSUE TITLE
Use semantic versioning

### ISSUE THREAD

**Issue by synthead** [shlomif/perl-Config-IniFiles#9]
Version numbers like 3.000003 are confusing.  I suggest that sematic versioning be used instead: https://semver.org/

If semantic versioning is used, implementing it would be a backward-compatible feature, so I suggest the next version to be 3.1.0.

**Comment by shlomif** [comment]
Hi @synthead ! Thanks for the suggestion, but please see http://shlomifishswiki.branchable.com/Never_Try_to_Please_Everyone/ (and especially https://taskwarrior.org/docs/advice.html ) and https://www.nntp.perl.org/group/perl.module-authors/2012/05/msg9650.html .

**Comment by shlomif** [comment]
Note that I am quite a fan of semver and usually use a version scheme based on it, but it is possible that CPAN and downstream tools won't handle the change well and that I'm afraid of changing a horse at midwater.

**Comment by shlomif** [comment]
No reply. Closing.
